{
 "title": "Polybot Dashboard Logs",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "[1h] Logs by Level",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (level) (count_over_time({service_name=\"polybot\"} | json | level!=\"\" [1h]))\n"
    }
   ]
  },
  {
   "title": "Logs Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (service_name)(\n  rate({service_name=\"polybot\"}[5m])\n) * 60"
    }
   ]
  },
  {
   "title": "Recent Errors",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"polybot\"}\n| json\n| level=\"error\"\n| line_format \"{{.message}} | err={{.attributes.context.error}} | job={{.attributes.context.jobId}} | wallet={{.attributes.context.walletId}}\""
    }
   ]
  }
 ]
}