ARG VERSION=11.5.2

FROM grafana/grafana-oss:${VERSION}

COPY datasources /etc/grafana/provisioning/datasources
# copy provisioning configs and bundled dashboards
COPY dashboards.yml /etc/grafana/provisioning/dashboards/dashboards.yml
COPY dashboards /etc/grafana/provisioning/dashboards/builtin
